dist: focal
language: cpp
cache: ccache

branches:
  only:
    - master
    - master_coverity_scan
    - /^stable-.*$/

os:
  - linux

addons:
  apt:
    packages:
      # Compilers:
      - gcc
      - g++
      - gcc-10
      - g++-10
      #- clang already installed by Travis
      # Tools:
      - cmake
      # Libraries:
      - libclucene-dev
      - libsword-dev
      # System Qt:
      - libqt5svg5-dev
      - libqt5xmlpatterns5-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev
      - qtwebengine5-dev
      # Documentation:
      - fop
      - po4a
      - xsltproc
      - docbook-xml
      - docbook-xsl
  coverity_scan:
    project:
      name: "bibletime/bibletime"
      description: "BibleTime build submitted via Travis CI"
    notification_email: jaak+coverity-scan-travis-ci@ristioja.ee
    build_command_prepend: "mkdir b && cd b && cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/local/"
    build_command: "cmake --build ."
    branch_pattern: .*_coverity_scan

env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
     - secure: "FmufrIN8L4Ptfbn0Lw/1S7fKnPxpvv7t9KEN5XhQ3lwW5Qir7mGe2r87biaKyjo15VNc4bizA2wR63YUXz6JPMETwYPahKSlW2tAsHmJTOwyweNW7zkKf6Iwrf9vYaMZyOpR2jRkD9Ko8vd4BpIw4FF6X/vaJqfnvQyIOiDGFr8="
     - NUM_THREADS=2
  jobs:
     - CC=gcc CXX=g++
     - CC=gcc-10 CXX=g++-10
     - CC=clang CXX=clang++

before_install:
  - uname -a
  - test "$(uname -m)" == "aarch64" && USE_CCACHE=0 || USE_CCACHE=1

script:
  - if [ "0${COVERITY_SCAN_BRANCH}" != "01" ]; then mkdir b && cd b && cmake .. -DUSE_CCACHE=${USE_CCACHE} -DCMAKE_INSTALL_PREFIX=${HOME}/local && make -j2 VERBOSE=1 && make install; fi


notifications:
  irc: "irc.oftc.net#bibletime"
